#!/bin/bash

mode=${1:-"base"}

[[ $mode == "base" || $mode == "color" || $mode == "font" || $mode == "model" || $mode == "nes" || $mode == "paint" || $mode == "world" ]] || {
	echo error: unrecognized mode "$mode"
	exit 1
}

[[ $mode == "base" ]] && cd source
[[ $mode == "base" ]] || cd source/$mode

echo https://localhost:8000
python -m http.server --tls-cert /a/local/key/key.pem.pub --tls-key /a/local/key/key.pem
